### ISSUE TITLE
issue-1-user-can-see-their-car

### ISSUE THREAD

**Issue by edtan094** [edtan094/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] create a suitable background
- [x] set the car on the top left side of the page (where all elements will start)
- [x] ensure that the css styling is organized
