### ISSUE TITLE
issue-2-user-can-turn-their-car

### ISSUE THREAD

**Issue by edtan094** [edtan094/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] apply css to ensure that the car is able to rotate up, left, down, right
- [x] create an eventlistener that tells when the car to rotate
- [x] make sure the car faces the correct way as the user intends it when they hit the keyboard
- [x] ensure there are no bugs and remove an unnecessary styling and features
