### ISSUE TITLE
issue-3-user-can-start-their-car

### ISSUE THREAD

**Issue by edtan094** [edtan094/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] create a data model in js for the car
- [x] the data model should include the cars x and y coordinates on the page as well as the current direction its facing
- [x] Use the style property of element objects to change your car's top and left box offset styles
- [x] make sure the car moves straight from left to right
- [x] make sure the car moves when you want it to
- [x] clean up any errors and unneeded functionality
